### ISSUE TITLE
Compilation warning

### ISSUE THREAD

**Issue by pbzdyl** [deg/sodium#2]
Hi,

When cljs-compiling a project with sodium on classpath I am getting the following warning:

```
WARNING: Use of undeclared Var clojure.set/subset? at line 72 js/app.out/sodium/utils.cljc
```

I believe the CLJS implementation of `all-keys-valid?` cannot rely on `clojure.set/subset?` as it is not part of CLJS standard library.

**Comment by deg** [comment]
Thanks.

It looks like the problem can be fixed just by adding a :require of clojure.set to the namespace. See https://stackoverflow.com/questions/21367433/clojurescript-clojure-set

I’m not sure why Sodium works as is for me. I must have clojure.set somewhere else in my project or dependencies, I guess.

Since you have a failing case, could you try adding the :require into a PR if it works?

Thanks, and sorry for missing this!

**Comment by pbzdyl** [comment]
Yes, adding a `require` in `utils.cljc` helped. PR #3 submitted!

**Comment by deg** [comment]
Thanks!
